### ISSUE TITLE
Highest Card is incorrect

### ISSUE THREAD

**Issue by grappler** [grappler/JaaassQueen#41]
![image](https://user-images.githubusercontent.com/1785641/81468283-d1fce300-91de-11ea-849f-e365beefeda0.png)

**Comment by simonschlaeppi** [comment]
The issue occurs if no card of trumpf suit is in the stich

**Comment by simonschlaeppi** [comment]
The issue occurs with the combination of King and Ten, because 10 gets more points than King.

But King is ranked higher than Ten.

**Comment by grappler** [comment]
@CelineMathis I thought you said the number of points was the deciding factor not the rank?

Is there ever a situation where there could be a problem if two cards have  the same score?

**Comment by CelineMathis** [comment]
I tried to say that the rank is the deciding factor- I forgot to mention that king and queen is sorted by rank as well besides 8,7 and 6. But you need to determine the highest card by the rank- everything else is too complicated. Sometimes the rank and the values are sorted very similarly. 

Yes. If someone plays HT and then someone else plays DT (and then 6H, 8H). These two cards (HT and DT) theoretically have the same value and score. But because hearts wins (in this heart stitch), HT is the highest card thus far. Does that make sense?

**Comment by CelineMathis** [comment]
In this exact scenario ST and CT are both valued at 10 points. The ST doesn't even matter because it has a different color than the minor suit being played (clubs). The CT is the second highest card in this one because the King ranks the highest- even though he has less points (4 in comparison to 10).
This shows both the scenario that ranking highest is the kind (due to rank not points) and that there can be two cards with the same value- but since they rank lower it doesn't matter.
